.PHONY: clean All

All:
	@echo "----------Building project:[ coan - Debug ]----------"
	@$(MAKE) -f  "coan.mk"
clean:
	@echo "----------Cleaning project:[ coan - Debug ]----------"
	@$(MAKE) -f  "coan.mk" clean
